CREATE DATABASE Adventure4You;
GO

USE Adventure4You;
GO

CREATE TABLE Users (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	Password NVARCHAR(64) NOT NULL,
);

CREATE TABLE UserLinks (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UserId INT NOT NULL,
	TeamId INT,
	RaceId INT
);

CREATE TABLE Races (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    CoordinatesCheckEnabled BIT NOT NULL,
	SpecialTasksAreStage BIT NOT NULL
);

CREATE TABLE Stage (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL	
);

CREATE TABLE StageLinks (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	StageId INT NOT NULL,
	RaceId INT NOT NULL
);

CREATE TABLE Points (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
	Value INT NOT NULL,
    Coordinates NVARCHAR(255)
);

CREATE TABLE PointLinks (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PointId INT NOT NULL,
	StageId INT NOT NULL,
);

CREATE TABLE Teams (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL
);

CREATE TABLE TeamLinks (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TeamId INT NOT NULL,
    RaceId INT NOT NULL
);

CREATE TABLE TeamPointsVisited (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PointId INT NOT NULL,
	TeamId INT NOT NULL
);